# Generated by Django 2.0.1 on 2018-02-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_compare', '0003_auto_20180130_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardranking',
            name='id',
        ),
        migrations.AlterField(
            model_name='cardranking',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mtg_compare.Card'),
        ),
    ]
