# Generated by Django 2.0.1 on 2018-03-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='mtg_compare/images/Card_Back.jpg', upload_to='card_images'),
        ),
    ]
