# Generated by Django 2.0.1 on 2018-03-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_compare', '0002_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='code',
            field=models.CharField(default='AAA', help_text='Enter the expansion code', max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='card_images/Card_Back.jpg', upload_to='card_images'),
        ),
    ]
