# Generated by Django 2.0.1 on 2018-03-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_compare', '0003_auto_20180303_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcolor',
            name='colorAbrv',
            field=models.CharField(default='C', help_text='Enter the abbreviation for the color', max_length=2),
        ),
    ]
